version: '3.8'

services:
  zap:
    image: owasp/zap2docker-stable:latest
    container_name: koepon-zap-scanner
    networks:
      - koepon-security
    volumes:
      - ./zap-reports:/zap/wrk:rw
      - ./zap-scripts:/zap/scripts:ro
    environment:
      - ZAP_PORT=8080
    ports:
      - "8080:8080"
    command: >
      bash -c "
        zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true &&
        sleep 10 &&
        zap-cli --zap-url http://localhost:8080 open-url http://host.docker.internal:3000 &&
        zap-cli --zap-url http://localhost:8080 spider http://host.docker.internal:3000 &&
        zap-cli --zap-url http://localhost:8080 active-scan http://host.docker.internal:3000 &&
        zap-cli --zap-url http://localhost:8080 report -o /zap/wrk/security-report.html -f html &&
        zap-cli --zap-url http://localhost:8080 report -o /zap/wrk/security-report.json -f json
      "
    depends_on:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web:
    build:
      context: ../client
      dockerfile: Dockerfile
    container_name: koepon-web-test
    networks:
      - koepon-security  
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - SECURITY_TEST_MODE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  koepon-security:
    driver: bridge